
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["APP_DATABASE_PASSWORD"] %> 
  port: <%= ENV["APP_PORT"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
  <<: *default
  database: RailsFlix_development

test:
  <<: *default
  database: RailsFlix_test


production:
  <<: *default
  database: RailsFlix_production
  username: RailsFlix
  password: <%= ENV['RAILSFLIX_DATABASE_PASSWORD'] %>
